### ISSUE TITLE
Add MDX format support? Or at least allow *.mdx file extension

### ISSUE THREAD

**Issue by Den-Rimus** [shuzijun/markdown-editor#99]
We have some fancy framework for our API documentation website - it works on top of Markdown format. Files have `*.mdx` extension and are, in fact, 90% markdown with some special blocks that are recognized by that framework. If they are not recognized&processed - they are just text. MacDown app shows them like that and it is great because allows 95% of editing and preview.

This would be great to also do in your plugin because editing in well-known IntelliJ editor is way better than any other app.

**Comment by shuzijun** [comment]
I learned about *.mdx, and the plug-in cannot guarantee compatibility with this format.

According to your description, most of them are compatible with md. You can try to set the .mdx suffix to Markdown format, so that the plug-in can be edited with the plug-in.

<img width="982" alt="image" src="https://github.com/shuzijun/markdown-editor/assets/27667179/bcff4ead-1ce7-4da4-ab86-759473463b78">

**Comment by pthurmond-vmlyr** [comment]
That does work. Though then a separate MDX entry in that list had to be cleared. Unclear how that might affect other features yet. Possibly adding support for the MDX entry itself might be useful. That said, that might be coming from a different plugin. Not sure.
